### PR TITLE
Fix Mirage logging Qunit integration

### LINKED ISSUE #52: Mirage logging from qunit is no longer respected
Most of this file https://github.com/bgantzler/ember-mirage/blob/v0.3.3-ember-mirage/ember-mirage/src/start-mirage.js no longer is present in 0.4.0

This code 
```
if (!env) {
    assert(
      'You must pass `owner` to startMirage() to lookup environment',
      owner,
    );
    env = owner.resolveRegistration('config:environment');
  }

  let environment = env.environment;

  let options = {
    env,
    environment,
```
was in support of this mirage facility https://miragejs.com/docs/testing/application-tests/#the-test-environment.   What is the correct way to do it now?

This code 
```
// Check to see if mirageLogging is on the URL. If so, enable logging on the server
  if (
    typeof location !== 'undefined' &&
    location.search.indexOf('mirageLogging') !== -1
  ) {
    server.logging = true;
  }

```
Supported setting the logging from the checkbox inserted into qunit. if they chose to include this code
```
if (dependencySatisfies('ember-qunit', '*')) {
  window.QUnit.config.urlConfig.push({
    id: 'mirageLogging',
    label: 'Mirage logging',
  });
}
```
in the test-support.js file.   What is the correct way of turning on and off logging for all tests. Are we opposed to adding the code 
```
// Check to see if mirageLogging is on the URL. If so, enable logging on the server
  if (
    typeof location !== 'undefined' &&
    location.search.indexOf('mirageLogging') !== -1
  ) {
    server.logging = true;
  }
```
after this line https://github.com/bgantzler/ember-mirage/blob/v0.4.0-ember-mirage/ember-mirage/src/test-support/setup-mirage.js#L30

Mirage seems to only allow the logging to be set after the server is created https://miragejs.com/api/classes/server/#logging

### PR DESCRIPTION
**Pull request by nickschot**
Fixes #52

### CODE REVIEW

File: ember-mirage/src/test-support/setup-mirage.js [hunk 1]
```diff
@@ -28,6 +28,11 @@ export function setupMirage(hooks = self, { createServer, config }) {
     }
 
     this.server = await createServer(config ?? {});
+
+    // This only works after the server was created.
+    this.server.logging =
```
Comment (NullVoxPopuli) [inline ember-mirage/src/test-support/setup-mirage.js:33]: I've been enabling logging via the call site.

For someone who is setting logging themselves, how do we not stomp on them?

Maybe, only set if the qp is set?

Comment (nickschot) [reply ember-mirage/src/test-support/setup-mirage.js:33]: Yeah this is something I was wondering about as well (and in part why this was a draft until just now 😂 ). It did seem that, when I was setting this up anyway, logging was enabled _by default_ when not explicitly passing false, so only setting it when the QP is set wouldn't work as far as I could see.

Comment (nickschot) [reply ember-mirage/src/test-support/setup-mirage.js:33]: While we figure this out, let me split the ember-qunit peerdep into a separate PR as that's required regardless to fix the existing bit of code.

Comment (NullVoxPopuli) [inline ember-mirage/src/test-support/setup-mirage.js:33]: can we wrap this in an if condition checking if `mirageLogging` is in the URL?

otherwise, we override always

Comment (nickschot) [reply ember-mirage/src/test-support/setup-mirage.js]: Just tried again locally and now it doesn't seem to log if I do that... not sure what was going on before. Should be good now then.

**Review by NullVoxPopuli — APPROVED** [review]

**Review by NullVoxPopuli — APPROVED** [review]
